name: ansi-poc
on:
  workflow_dispatch:

jobs:
  p:
    runs-on: ubuntu-latest
    steps:
      - run: |
          printf 'ANSI_LOG_START
'
          printf $'\033[31mRED_TEXT\033[0m\n'
          printf $'\033]0;PWNED_TITLE\007\n'
          printf 'ANSI_LOG_END
'
